policy: "both"


data:
  start_date: "2021_12_24"
  end_date: "2021_12_26"
decision_grid:
  env: 
      spaces:
        action_space: NormalizedAction
        observation_space: 
          type: "linear"
          # params: EverythingLinearSpaceAS
          params: EverythingLinearSpace

      reward_space: pnl 
      params:
        inv_envs: 1
        time_envs: 1
        as_expert_params:
          max_order_size: 5
          tick_size: 0.0001
          max_ticks: 10
          price_decimals: 4
          inventory_target: 0
          risk_aversion: 0.2
          order_size: 1
  model_name: delta_inventory_pnlreward_1684931119_init
  distinct_count_per_variable: 50
  constant_values:
    # as_bid: 0
    # as_ask: 0
    inventory: 0
    intensity: 0.594 # Average
    volatility: -0.73 # Average
    osi: 0.286 # Average
    order_book_imbalance: -0.022 # Average
    # current_second: -0.017 # Average
    # current_minute: -0.017 # Average
    current_hour: -0.0447 # Average

  model_kwargs:
    learning_rate: 7.047920836644666e-05
    n_steps: 1024
    batch_size: 2048
    n_epochs: 20
    gamma: 0.995
    gae_lambda: 0.9
    clip_range: 0.5
    normalize_advantage: true
    ent_coef: 1.0e-05
    vf_coef: 0.2566598626828248
    max_grad_norm: 1.0
    sde_sample_freq: 8

venv:
  random: 1

expert_params:
  max_order_size: 5
  tick_size: 0.0001
  max_ticks: 10
  price_decimals: 4
  inventory_target: 0
  risk_aversion: 0.2
  order_size: 1
