# list always represents a search space
x: ["choice", [1,2,3,4]]
y: ['uniform', 0,1]

# a constant value is added as a fixed val
z: 42

# dict is added iteratively
w: 
  a: 1
  b: 2

# dict --> iterate
iterate:
  # list --> search space under the dict
  learning_rate:
    ['uniform', 0,1]
  stuff:
    ['choice', [1,2]]

model:
  algo: ["choice", ["A2C", "PPO"]]
  params:
    PPO: 
      steps: ["choice", [1,2,3]]
    A2C:
      jumps: ["choice": [1,2]]
  selected_params: tune.sample_from()