# test_trade_size_price
data:
  start_date: "2021_12_24"
  end_date: "2021_12_26"

env: 
    spaces:
      action_space: NormalizedAction
      observation_space: 
        type: "linear"
        params: EverythingLinearSpace
    reward_space: inventory_integral_penalty 
    params:
      inv_envs: 1
      time_envs: 1
venv:
    random: 1


# test_execute_trade
env_trade:
  spaces:
      action_space: NormalizedAction
  

# test_single_env
env_single: 
    spaces:
      action_space: NormalizedAction
      observation_space: 
        type: "linear"
        params: SimpleLinearSpace
    reward_space: inventory_integral_penalty 
    params:
      inv_envs: 1
      time_envs: 1
      n_envs: 1
      use_copy_envs: True

# test_multi_env
env_multi: 
    spaces:
      action_space: NormalizedAction
      observation_space: 
        type: "linear"
        params: SimpleLinearSpace
    reward_space: inventory_integral_penalty 
    params:
      inv_envs: 1
      time_envs: 1
      n_envs: 5
      use_copy_envs: True

# test_everything_linear_as
env_everything_linear_as: 
    spaces:
      action_space: NormalizedAction
      observation_space: 
        type: "linear"
        params: EverythingLinearSpaceAS
    reward_space: inventory_integral_penalty 
    params:
      inv_envs: 1
      time_envs: 1
      n_envs: 1
      use_copy_envs: True
      as_expert_params:
        max_order_size: 5
        tick_size: 0.0001
        max_ticks: 10
        price_decimals: 4
        inventory_target: 0
        risk_aversion: 0.2
        order_size: 1


# test_everything_linear_as_parallel
env_everything_linear_as_parallel: 
    spaces:
      action_space: NormalizedAction
      observation_space: 
        type: "linear"
        params: EverythingLinearSpaceAS
    reward_space: inventory_integral_penalty 
    params:
      inv_envs: 6
      time_envs: 5
      inv_jump: 0.1
      as_expert_params:
        max_order_size: 5
        tick_size: 0.0001
        max_ticks: 10
        price_decimals: 4
        inventory_target: 0
        risk_aversion: 0.2
        order_size: 1

expert_params:
  max_order_size: 5
  tick_size: 0.0001
  max_ticks: 10
  price_decimals: 4
  inventory_target: 0
  risk_aversion: 0.2
  order_size: 1