# test_run_rollout_end
data:
  start_date: "2021_12_24"
  end_date: "2021_12_25"

env: 
    spaces:
      action_space: NormalizedAction
      observation_space: 
        type: "linear"
        params: EverythingLinearSpace
    reward_space: inventory_integral_penalty 
    params:
      inv_envs: 1
      time_envs: 1
venv:
    random: 1

model:
  model_name: 65a1b752e751883064026f436beb8335

parallel_callback: 
    inv_envs: 1
    time_envs: 5
    inv_jump: 0.15