# TEST 1
data:
  start_date: "2021_12_24"
  end_date: "2021_12_26"

env: 
    spaces:
      action_space: NormalizedAction
      observation_space: 
        type: "linear"
        params: SimpleLinearSpace
    reward_space: pnl 
    params:
      inv_envs: 1
      time_envs: 1
venv:
    random: 1

# TEST 2
env_parallel: 
    spaces:
      action_space: NormalizedAction
      observation_space: 
        type: "linear"
        params: SimpleLinearSpace
    reward_space: pnl 
    params:
      inv_envs: 2
      time_envs: 1

  

expert_params:
  max_order_size: 5
  tick_size: 0.0001
  max_ticks: 10
  price_decimals: 4
  inventory_target: 0
  risk_aversion: 0.2
  order_size: 1

test_2_env: 
  spaces:
    action_space: NormalizedAction
    observation_space: 
      type: "linear"
      params: EverythingLinearSpace
  reward_space: pnl 
  params:
    n_envs: 2
    use_copy_envs: true